name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sbom:
    uses: ./.github/workflows/sbom.yml
    permissions:
      contents: read

  sca:
    uses: ./.github/workflows/sca.yml
    needs: [ sbom ]
    with:
      sbom_artifact: ${{ needs.sbom.outputs.sbom_artifact }}

  sast:
    uses: ./.github/workflows/sast.yml
    permissions: 
      contents: read
      security-events: write
      actions: read
      
  secrets:
    uses: ./.github/workflows/secrets.yml
    permissions:
      contents: read

  build:
    uses: ./.github/workflows/build.yml
    permissions: 
      contents: read

  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: 
      contents: read
      packages: write
      security-events: write

  signing:
    needs: [container_build]
    uses: ./.github/workflows/sign-image.yml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      backend-image-digest: ${{ needs.container_build.outputs.backend-image-digest }}
