name: SBOM Generation

on:
  workflow_dispatch: 
  workflow_call:

jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    outputs:
      sbom_artifact: ${{ steps.upload-artifact.outputs.artifact-name}}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment
        run: python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          # Syft installieren
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          # SBOM erstelllen
          syft ./venv/lib/python3.11/site-packages -o spdx-json > sbom.spdx.json

      - name: Upload SBOM artifact
        id: upload-artifact
        uses: actions/upload-artifact@v5
        with:
          name: sbom_${{ github.run_id }}
          path: sbom.spdx.json
          retention-days: 30
